# Generated by Django 3.1.5 on 2021-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приюта'),
        ),
    ]
