# Generated by Django 3.1.5 on 2021-03-01 11:29

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='None', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='None', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='unknown', max_length=100, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='no name', max_length=100, verbose_name='Кличка'),
        ),
    ]
