# Generated by Django 3.1.5 on 2021-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20210111_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-surname'], 'verbose_name': 'Хозяин', 'verbose_name_plural': 'Хозяева'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='photo',
            name='uplaod_date',
            field=models.DateField(auto_now=True, verbose_name='Дата загрузки фото'),
        ),
    ]
