# Generated by Django 3.1.5 on 2021-03-04 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20210303_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=pets.models.path_for_pet_img, validators=[django.core.validators.validate_image_file_extension], verbose_name='Фото'),
        ),
    ]
