# Generated by Django 3.1.5 on 2021-01-11 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20210111_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.BigIntegerField(blank=True, help_text='ТОЛЬКО цифры', null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-surname'],
            },
        ),
        migrations.CreateModel(
            name='ShelteredPets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheltered_date', models.DateField(default=datetime.date.today, verbose_name='Дата приюта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='pets.client')),
            ],
            options={
                'verbose_name': 'Устроенные животные',
                'verbose_name_plural': 'Устроенные животные',
                'ordering': ['sheltered_date'],
            },
        ),
        migrations.RemoveField(
            model_name='pet',
            name='exit_date',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='shelteredpets',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.pet'),
        ),
    ]
