# Generated by Django 3.1.5 on 2021-01-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20210112_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteredpets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owners', to='pets.client'),
        ),
        migrations.AlterField(
            model_name='shelteredpets',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pets', to='pets.pet'),
        ),
    ]
