# Generated by Django 3.1.5 on 2021-01-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20210112_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteredpets',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.pet', verbose_name='Питомец'),
        ),
    ]
