# Generated by Django 3.1.5 on 2021-01-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20210112_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['surname'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name'], 'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
    ]
