# Generated by Django 3.1.5 on 2021-01-12 08:47

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20210112_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=pets.models.path_for_pet_img, verbose_name='Аватар'),
        ),
    ]
