# Generated by Django 3.1.5 on 2021-01-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_auto_20210112_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelteredpets',
            options={'ordering': ['-sheltered_date'], 'verbose_name': 'Устроенные животные', 'verbose_name_plural': 'Устроенные животные'},
        ),
    ]
